export type NavItem = { slug: string; num: string; label: string; part: number };

export const partLabels: Record<number, string> = {
  1: "زمینه و شهود",
  2: "خط داستانیِ اصلی",
  3: "یادگیری تداعی و رقابتی",
  4: "مطالعات موردی و عملی",
  5: "پیوست‌ها",
};

export const navItems: NavItem[] = [
  { slug: "1", num: "۰۱", label: "مقدمه", part: 1 },
  { slug: "2", num: "۰۲", label: "مدل نورون و معماری", part: 1 },
  { slug: "3", num: "۰۳", label: "مثال روشنگر", part: 1 },
  { slug: "4", num: "۰۴", label: "قاعده‌ی یادگیری پرسپترون", part: 2 },
  { slug: "5", num: "۰۵", label: "فضای برداری سیگنال و وزن", part: 2 },
  { slug: "6", num: "۰۶", label: "تبدیل‌های خطی", part: 2 },
  { slug: "7", num: "۰۷", label: "یادگیری هبی نظارت‌شده", part: 2 },
  { slug: "8", num: "۰۸", label: "سطوح عملکرد", part: 2 },
  { slug: "9", num: "۰۹", label: "بهینه‌سازی عملکرد", part: 2 },
  { slug: "10", num: "۱۰", label: "یادگیری Widrow-Hoff", part: 2 },
  { slug: "11", num: "۱۱", label: "بک‌پروپاگیشن", part: 2 },
  { slug: "12", num: "۱۲", label: "تغییرات بک‌پروپاگیشن", part: 2 },
  { slug: "13", num: "۱۳", label: "تعمیم‌پذیری", part: 2 },
  { slug: "14", num: "۱۴", label: "شبکه‌های پویا", part: 2 },
  { slug: "15", num: "۱۵", label: "یادگیری تداعی", part: 3 },
  { slug: "16", num: "۱۶", label: "شبکه‌های رقابتی", part: 3 },
  { slug: "17", num: "۱۷", label: "شبکه‌ی پایه‌ی شعاعی", part: 3 },
  { slug: "18", num: "۱۸", label: "شبکه‌ی گراسبرگ", part: 3 },
  { slug: "19", num: "۱۹", label: "نظریه‌ی تشدید تطبیقی", part: 3 },
  { slug: "20", num: "۲۰", label: "پایداری", part: 3 },
  { slug: "21", num: "۲۱", label: "شبکه‌ی هاپفیلد", part: 3 },
  { slug: "22", num: "۲۲", label: "مسائل عملی آموزش", part: 4 },
  { slug: "23", num: "۲۳", label: "موردی: تقریب تابع", part: 4 },
  { slug: "24", num: "۲۴", label: "موردی: تخمین احتمال", part: 4 },
  { slug: "25", num: "۲۵", label: "موردی: تشخیص الگو", part: 4 },
  { slug: "26", num: "۲۶", label: "موردی: خوشه‌بندی", part: 4 },
  { slug: "27", num: "۲۷", label: "موردی: پیش‌بینی", part: 4 },
  { slug: "app-a", num: "پ.الف", label: "پیوست الف: کتاب‌نامه", part: 5 },
  { slug: "app-b", num: "پ.ب", label: "پیوست ب: فرهنگ نمادها", part: 5 },
  { slug: "app-c", num: "پ.ج", label: "پیوست ج: نرم‌افزار", part: 5 },
];
