export type NavItem = { slug: string; num: string; label: string };

export const navItems: NavItem[] = [
  { slug: "1", num: "۰۱", label: "مقدمه" },
  { slug: "2", num: "۰۲", label: "مدل نورون و معماری" },
  { slug: "3", num: "۰۳", label: "مثال روشنگر" },
  { slug: "4", num: "۰۴", label: "قاعده‌ی یادگیری پرسپترون" },
  { slug: "5", num: "۰۵", label: "فضای برداری سیگنال و وزن" },
  { slug: "6", num: "۰۶", label: "تبدیل‌های خطی" },
  { slug: "7", num: "۰۷", label: "یادگیری هبی نظارت‌شده" },
  { slug: "8", num: "۰۸", label: "سطوح عملکرد" },
  { slug: "9", num: "۰۹", label: "بهینه‌سازی عملکرد" },
  { slug: "10", num: "۱۰", label: "یادگیری Widrow-Hoff" },
  { slug: "11", num: "۱۱", label: "بک‌پروپاگیشن" },
  { slug: "12", num: "۱۲", label: "تغییرات بک‌پروپاگیشن" },
  { slug: "13", num: "۱۳", label: "تعمیم‌پذیری" },
  { slug: "14", num: "۱۴", label: "شبکه‌های پویا" },
  { slug: "15", num: "۱۵", label: "یادگیری تداعی" },
  { slug: "16", num: "۱۶", label: "شبکه‌های رقابتی" },
  { slug: "17", num: "۱۷", label: "شبکه‌ی پایه‌ی شعاعی" },
  { slug: "18", num: "۱۸", label: "شبکه‌ی گراسبرگ" },
  { slug: "19", num: "۱۹", label: "نظریه‌ی تشدید تطبیقی" },
  { slug: "20", num: "۲۰", label: "پایداری" },
  { slug: "21", num: "۲۱", label: "شبکه‌ی هاپفیلد" },
  { slug: "22", num: "۲۲", label: "مسائل عملی آموزش" },
  { slug: "23", num: "۲۳", label: "موردی: تقریب تابع" },
  { slug: "24", num: "۲۴", label: "موردی: تخمین احتمال" },
  { slug: "25", num: "۲۵", label: "موردی: تشخیص الگو" },
  { slug: "26", num: "۲۶", label: "موردی: خوشه‌بندی" },
  { slug: "27", num: "۲۷", label: "موردی: پیش‌بینی" },
  { slug: "app-a", num: "پ.الف", label: "پیوست الف: کتاب‌نامه" },
  { slug: "app-b", num: "پ.ب", label: "پیوست ب: فرهنگ نمادها" },
  { slug: "app-c", num: "پ.ج", label: "پیوست ج: نرم‌افزار" },
];
